language: node_js
node_js:
- '0.12'
- '0.11'
- '0.10'
- '0.8'
- iojs
matrix:
  fast_finish: true
before_install:
- node test/scripts/npm.js
- npm install -g grunt-cli
script:
- grunt ci
- grunt coveralls:push
deploy:
  provider: npm
  email: simon@simonemms.com
  api_key:
    secure: scvV1vsf/S4OgeXjKysHViN4cVjyZQYo+nzl0UY9DsDeYCVoEijnTN4zR46eC7CVCXiUL13kc8VSqmk0w/9ZHNnj37fGE9wfRAuMNGmqIzi8in4ZTaGip/OxKtjW3mmWnst7HyR92C6mo0HtBa1BFa2jw8fhi8TmSbktTvW7UIo=
  on:
    all_branches: true
    tags: true
    repo: slash-dev-slash-null/steeplejack
