language: node_js
node_js:
- '0.12'
- '0.11'
- '0.10'
- '0.8'
- 'iojs'
- 'iojs-v1.0.4'
- 'iojs-v1.1.0'
- 'iojs-v1.2.0'
- 'iojs-v1.3.0'
- 'iojs-v1.4.0'
- 'iojs-v1.5.1'
- 'iojs-v1.6.4'
- 'iojs-v1.7.1'
- 'iojs-v1.8.1'
- 'iojs-v2.0.1'
matrix:
  fast_finish: true
sudo: false
before_install:
- node test/scripts/npm.js
- npm install -g grunt-cli
script:
- grunt ci
- grunt coveralls:push
deploy:
  provider: npm
  email: simon@simonemms.com
  api_key:
    secure: scvV1vsf/S4OgeXjKysHViN4cVjyZQYo+nzl0UY9DsDeYCVoEijnTN4zR46eC7CVCXiUL13kc8VSqmk0w/9ZHNnj37fGE9wfRAuMNGmqIzi8in4ZTaGip/OxKtjW3mmWnst7HyR92C6mo0HtBa1BFa2jw8fhi8TmSbktTvW7UIo=
  on:
    all_branches: true
    tags: true
    repo: slash-dev-slash-null/steeplejack
