language: node_js
node_js:
- '0.11'
- '0.10'
- '0.8'
matrix:
  fast_finish: true
before_install:
- npm update -g npm
- npm install -g grunt-cli
script:
- grunt ci
deploy:
  provider: npm
  api_key: cmlnZ2VydGhlZ2VlazpkdWV0b2U4Mg==
  on:
    tags: true
