# Site settings
title: steeplejack
description: > #
  steeplejack is a scaffolding framework for node.js/io.js that adds
  awesomity to your projects - IOC container, data models and collections,
  URL routing and class inheritance for grown-ups - all out of the box.
baseurl: "/steeplejack"
url: "https://slash-dev-slash-null.github.io"

# Build settings
markdown: kramdown

nav:
    -
        name: "Home"
        url: "/"
    -
        name: "Documentation"
        url: "/documentation/"
