# Site settings
title: steeplejack
description: > #
  steeplejack is a scaffolding framework for node.js/io.js that adds
  awesomity to your projects - IOC container, data models and collections,
  URL routing and class inheritance for grown-ups - all out of the box.
baseurl: "/steeplejack"
url: "https://slash-dev-slash-null.github.io"

# Build settings
markdown: kramdown

nav:
    -
        name: "Home"
        url: "/"
    -
        name: "Documentation"
        url: "/docs/"

docs:
    -
        title: "Getting Started"
        items:
            -
                name: "Installation"
                url: "/docs/getting-started/"
            -
                name: "Your First App"
                url: "/docs/getting-started/your-first-app/"
            -
                name: "Routing"
                url: "/docs/getting-started/routing/"
            -
                name: "Models and Collections"
                url: "/docs/getting-started/models-and-collections/"
    -
        title: "API Reference"
        items:
            -
                name: "HTTP Strategies"
                url: "/docs/http-strategies"
            -
                name: "IOC Container"
                url: "/docs/ioc-container/"
            -
                name: "Router"
                url: "/docs/router/"
